
require conf/machine/beaglebone-yocto.conf

MACHINEOVERRIDES =. "beaglebone-yocto:"

KERNEL_DEVICETREE = "ti/omap/am335x-roomplayer-plus.dtb"

KERNEL_IMAGETYPE = "uImage"

UBOOT_MACHINE = "am335x_evm_defconfig"

UBOOT_LOADADDRESS = "0x80008000"
UBOOT_ENTRYPOINT = "0x80008000"

IMAGE_BOOT_FILES = "uImage am335x-roomplayer-plus.dtb rfspart bootargs"

INITRAMFS_IMAGE_BUNDLE = "1"