#TODO
#require conf/machine/beaglebone-yocto.conf

MACHINEOVERRIDES =. "roomplayer-i-ii:"

#TODO
#KERNEL_DEVICETREE_roomplayer-plus += "ti/omap/am335x-roomplayer-plus.dtb"

#TODO
#UBOOT_MACHINE = "am335x_evm_config"