LCONF_VERSION = "7"

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-simpleaudio"
BBFILE_PATTERN_meta-simpleaudio := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-simpleaudio = "6"

LAYERSERIES_COMPAT_meta-simpleaudio = "scarthgap"