#!/bin/sh

echo "Starting custom initramfs..."

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /run

udhcpc

echo "Press ENTER within 10 seconds to drop to shell, otherwise flashing starts..."
if read -t 10 input; then
    echo "Dropping to shell..."
    exec /bin/sh
fi

mkdir -p /mnt/root
if ! mount /dev/mmcblk0p2 /mnt/root 2>/dev/null; then
    echo "ERROR: Could not mount rootfs!"
    goto_flash=1
else
    if [ ! -f /mnt/root/simpleaudio-port-installed ]; then
        echo "/simpleaudio-hifiberry-installed not found!"
        goto_flash=1
    else
        goto_flash=0
    fi
fi

if [ "$goto_flash" -eq 1 ]; then

    echo "Starting flashing mode"
    IMAGE=/images/rootfs.wic.gz
    if [ -f $IMAGE ]; then
        echo "Flashing $IMAGE to /dev/mmcblk0 ..."
        zcat $IMAGE | dd of=/dev/mmcblk0 bs=4M status=progress conv=fsync
        sync
        echo "Flash complete, rebooting..."
        exec reboot -f
    else
        echo "ERROR: Flash image not found!"
        exec /bin/sh
    fi
fi

echo "Rootfs OK, continuing boot..."

mount --move /proc /mnt/root/proc
mount --move /sys /mnt/root/sys
mount --move /dev /mnt/root/dev
mount --move /run /mnt/root/run

exec switch_root /mnt/root /sbin/init