#!/bin/sh
#
#Config done as followed:
#/usr/bin/setgpio GPIONUMBER INPUT(0)/OUTPUT(1) FALSE(0)/TRUE(1)
#
#
################################Soundcard init############################
#Enable soundcard

gpioset -t0 soundcard=1

################################LEDs######################################

#Set white LED brightness

gpioset -t0 white-led=0
#Disable red LED
gpioset -t0 red-led=0

#Enable green LED
#First disable blinkgpio green LED
gpioset -t0 green-led-blink=0
gpioset -t0 green-led=1

#Green led blinking
#/usr/bin/setgpio 499 1 1
#Not enabled, just here for completeness.

################################################################

########################Configure Sound I/O#####################
#enable line-out
gpioset -t0 line-out=1

#Enable headphone out
gpioset -t0 headphone=1

#Enable amplifier
gpioset -t0 amplifier=1

###############################################################

######################Inputs##################################

#The following GPIOs are used as inputs.

#True if player with amplifier - only naming given, nothing to be set.
#If board with amplifier

#amplifier-in

#headphone-in

#Line front plugged in

#line-front-in

#Side button

#side-button


####################Misc#####################################

#Enable/disable ethernet PHY (this will cause ethernet disconnection!)
#/usr/bin/setgpio 501 0 0

#Set EoP
#/usr/bin/eop_flash_ps

#############################################################
